#!/bin/bash

#----------------
# Name          : run_program
# Project       : scanz
# Description   : Executes the scanz program suite
# Author        : E Fournier
# Example Usage : ./run_program
#----------------

run_program() {
  bash "./_src/main.bash" "$@"
}

run_program "$@"

